# SimuInvest Imobiliário - Supabase Configuration
project_id = "kjcqoxlusfcndmdtjsks"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public", "storage", "graphql", "vault", "realtime"]
extra_search_path = ["public", "extensions"]
max_rows = 100000
external_url = "http://127.0.0.1:54321"

[api.tls]
enabled = false

[db]
port = 54322
shadow_port = 54320
major_version = 17

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://cd61e233-1bb9-4454-9d2c-cc412a1bd055.lovableproject.com/**", "https://id-preview--cd61e233-1bb9-4454-9d2c-cc412a1bd055.lovable.app/**", "https://invest-plan-optimize.lovable.app/**", "https://preview--invest-plan-optimize.lovable.app/**"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10

[auth.mfa]
max_enrolled_factors = 10

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true

[auth.mfa.phone]
enroll_enabled = false
verify_enabled = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true
secure_password_change = false
max_frequency = "1m0s"
otp_length = 6
otp_expiry = 86400

[auth.sms]
enable_signup = false
enable_confirmations = false

